services:
  patient-service-db:
    container_name: patient-service-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: patient-service-db
    expose:
      - "5432"
    volumes:
      - patient-service-data:/var/lib/postgresql
    networks:
      - patient-service-backend-network

  kafka:
    container_name: kafka
    image: apache/kafka:latest
    expose:
      - "9092"
    environment:
      KAFKA_NODE_ID: 0
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - patient-service-backend-network

  eureka-server:
    container_name: eureka-server
    build: ./eureka-server
    image: eureka-server:latest
    ports:
      - "8761:8761"
    networks:
      - patient-service-backend-network

  api-gateway:
    container_name: api-gateway
    build: ./api-gateway
    image: api-gateway:latest
    ports:
      - "4004:4004"
    depends_on:
      - patient-service
      - eureka-server
    networks:
      - patient-service-backend-network

  analytics-service:
    container_name: analytics-service
    build: ./analytics-service
    image: analytics-service:latest
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    expose:
      - "4002"
    depends_on:
      - kafka
      - eureka-server
    networks:
      - patient-service-backend-network

  billing-service:
    container_name: billing-service
    build: ./billing-service
    image: billing-service:latest
    expose:
      - "9002"
    networks:
      - patient-service-backend-network

  patient-service:
    container_name: patient-service
    build: ./patient-service
    image: patient-service:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/patient-service-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_PORT: 9002
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    expose:
      - "4001"
    depends_on:
      - patient-service-db
      - billing-service
      - kafka
      - analytics-service
      - eureka-server
    networks:
      - patient-service-backend-network

networks:
  patient-service-backend-network:

volumes:
  patient-service-data: